#!/bin/bash

#Setting up backend:
#
#First:
# Create ubuntu 14.04 instance
# t2.medium
# Protect against accidental termination
# Size: 30Gb [just have it as one image, easier to manage]
# Security group: Production backend
# keyfile: m.t.smith@sheffield.ac.uk_scikic1.pem

#install git
# sudo apt-get -y install git
#
#install anaconda (TODO: Anaconda might change version, update here).
# wget https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda-2.2.0-Linux-x86_64.sh
# bash Anaconda-2.2.0-Linux-x86_64.sh
#
#LOG OUT AND LOG BACK IN! (so Anaconda's changes can take effect)
#
#install scikic
# git clone https://github.com/scikic/scikic.git
# cd scikic
# ./backend_config_script

source ~/.bashrc #load new env variables
#install conda modules
conda install -y -c pymc pymc
conda install -y -c https://conda.binstar.org/jjhelmus pyproj
pip install overpy
pip install pyshp
sudo apt-get -y update
sudo apt-get -y install libgeos-dev
sudo apt-get -y install libopenblas-dev
conda install -y geos
conda install -y shapely

#for hosting etc
pip install gunicorn
sudo apt-get -y install nginx
sudo apt-get -y install gunicorn


#set up automatically starting, etc
sudo cp ~/scikic/scikic.conf /etc/init
sudo cp ~/scikic/nginx_default_conf /etc/nginx/sites-enabled/default
sudo cp ~/scikic/gunicorn_scikic.py /etc/gunicorn.d/scikic.py

#ensure location is available for data
mkdir ~/api-data
touch ~/api-data/logging.log
touch ~/api-data/error.log

sudo touch /var/log/nginx/scikic.log
sudo chown ubuntu /var/log/nginx/scikic.log
sudo chgrp ubuntu /var/log/nginx/scikic.log

sudo touch /var/log/gunicorn/error.log
sudo chown ubuntu /var/log/gunicorn/error.log
sudo chgrp ubuntu /var/log/gunicorn/error.log

sudo touch /var/log/gunicorn/access.log
sudo chown ubuntu /var/log/gunicorn/access.log
sudo chgrp ubuntu /var/log/gunicorn/access.log


sudo start scikic
sudo service nginx restart

#initialise the database (this will take a LONG time)
cd ~/scikic
python setup.py
