#!/bin/bash

#Run this on an AWS ubuntu instance, with a volume attached at /dev/xvdf

#install software (git will already be installed, to get this file)
sudo apt-get update
sudo apt-get -y install git

#install anaconda (TODO: Anaconda might change version, update here).
cd ~
wget https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda-2.2.0-Linux-x86_64.sh
bash Anaconda-2.2.0-Linux-x86_64.sh

source ~/.bashrc #load new env variables
#install conda modules
conda install -y -c pymc pymc
conda install -y -c https://conda.binstar.org/jjhelmus pyproj
pip install overpy
pip install pyshp
sudo apt-get -y update
sudo apt-get -y install libgeos-dev
sudo apt-get -y install libopenblas-dev
conda install -y geos
conda install -y shapely

#ensure location is available for data
mkdir ~/api-data
touch ~/api-data/logging.log
touch ~/api-data/error.log

#initialise the database (this will take a LONG time)
cd ~/scikic
python setup.py
